
name: workflow for running my first github actions
on:
  pull_request:
    branches: [development]
    types: [closed]
  push:
    branches: [master]
env:
  ARM_CLIENT_ID: ${{secrets.ARM_CLIENT_ID}}
  ARM_CLIENT_SECRET: ${{secrets.ARM_CLIENT_SECRET}}
  ARM_SUBSCRIPTION_ID: ${{secrets.ARM_CLIENT_ID_SUBSCRIPTION_ID}}
  ARM_TENANT_ID: ${{secrets.TENANT_ID}}
  ACTIONS_STEP_DEBUG: true
jobs:
  myfirst:
    name: 'FIRST JOB'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash 
    steps:
    - name: print Runner Hostname
      run: hostname 
      shell: bash 
    - name: Print Runner IP Address
      run: curl -sL https://ipconfig.io
      shell: bash
    - name: Terraform fmt
      id: fmt
      run: terraform fmt -recursive

    - name: Terraform Init
      id: init
      run: terraform init -no-color

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color

    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color

    - name: Terraform Apply
      id: apply
      run: terraform apply -auto-approve -no-color  
  